export const colors = {
  COLOR_PRIMARY: "#f96163",
  COLOR_LIGHT: "#ffff",
  COLOR_DARK_ALT: "#262626",
};

const Categories=[
  {
    id: "01",
    category:'Breakfast',
  },

  {
  
    id: "02",
    category:'Lunch',
  },
  {
   
    id: "03",
    category:'Dinner',
  },
  {
    
    id: "04",
    category:'Asian',
  },
  {
    id: "05",
    category:'Italian',
  },
  {
    id: "06",
    category:'Desert',
  },
  {
    id: "07",
    category:'Vegetarian',
  },
  {
    id: "08",
    category:'Sea Food',
  },
  {
    id: "09",
    category:'Fried Rice',
  },
];
export default Categories;

export const recipeList = [
  {
    id: "01",
    name: "Fried Rice",
    image: require("../../assets/images/FriedRice.jpg"),
    rating: "4.2",
    ingredients: ["Rice", "Vegetable", "Piece Beans", "Vegatable Oil", "Salt and Seasoning", "Onion", "Cow Liver", "Green Pepper", "Green Beans" ],
    time: "45 mins",
    difficulty: "Medium",
    calories: "420 cal",
    color: "#adff2f",
    description: ["A good prepared fried rice win the soul of the customer"],
    steps:[
      "Cook the Fried Rice according to the package instructions.",
      "per boiled your rice for about 20mins and then sieve the water from it there after",
      "per boil the cow liver and dice it into desirable size, add little quantity of veg oil into your port and met it for 2mins",
      "Blend the green pepper with blender with a little water ",
      "pour the blending green pepper into the hot vegetable oil with your cow lever and mix it together and add seasoning to it with a little water",
      "allow it to boil for 4mins and then add back your per boil rice into it and cover it for another 15mins",
      "wash your carrot and green beans and dice them into very desirable size",
      "rinse your piece beans and open your can corn add everything and stir it together for 2min for all the igredient to mix properly.",
      "then your food is ready to serve",
    ],
  },
  {
    id: "02",
    name: "Semo And Vegetable Soup",
    image: require("../../assets/images/semo.jpeg"),
    rating: "4.2",
    ingredients: ["Corn flour", "Vegetable", "Egusi", "Palm Oil", "Salt and Seasoning", "Fish", "Cow Intestine" ],
    time: "45 mins",
    difficulty: "Medium",
    calories: "420 cal",
    color: "#cd5c5c",
    description: ["A good prepared fried rice win the soul of the customer"],
    steps:[
      "Cook the Fried Rice according to the package instructions.",
      "per boiled your rice for about 20mins and then sieve the water from it there after",
      "per boil the cow liver and dice it into desirable size, add little quantity of veg oil into your port and met it for 2mins",
      "Blend the green pepper with blender with a little water ",
      "pour the blending green pepper into the hot vegetable oil with your cow lever and mix it together and add seasoning to it with a little water",
      "allow it to boil for 4mins and then add back your per boil rice into it and cover it for another 15mins",
      "wash your carrot and green beans and dice them into very desirable size",
      "rinse your piece beans and open your can corn add everything and stir it together for 2min for all the igredient to mix properly.",
      "then your food is ready to serve",
    ],
  },
  {
    id: "03",
    name: "Yam and Egg Souce",
    image: require("../../assets/images/yamEgg.jpeg"),
    rating: "4.2",
    ingredients: ["Yam", "Vegetable Oil", "Salt and Seasoning", "Slice Onion", "Crumble Pepper", "Eggs" ],
    time: "25 mins",
    difficulty: "Fair",
    calories: "190 cal",
    color: "#48d1cc",
    description: ["A good prepared fried rice win the soul of the customer"],
    steps:[
      "Cook the Fried Rice according to the package instructions.",
      "per boiled your rice for about 20mins and then sieve the water from it there after",
      "per boil the cow liver and dice it into desirable size, add little quantity of veg oil into your port and met it for 2mins",
      "Blend the green pepper with blender with a little water ",
      "pour the blending green pepper into the hot vegetable oil with your cow lever and mix it together and add seasoning to it with a little water",
      "allow it to boil for 4mins and then add back your per boil rice into it and cover it for another 15mins",
      "wash your carrot and green beans and dice them into very desirable size",
      "rinse your piece beans and open your can corn add everything and stir it together for 2min for all the igredient to mix properly.",
      "then your food is ready to serve",
    ],
  },
  {
    id: "04",
    name: "Jollof Rice",
    image: require("../../assets/images/jollofrice.jpeg"),
    rating: "4.2",
    ingredients: ["Ric", "Vegetable Oil", "Salt and Seasoning", "Slice Onion", "Crumble Pepper", "Curry and Time", "butter", "Tomato" ],
    time: "25 mins",
    difficulty: "Fair",
    calories: "200 cal",
    color: "#ff6347",
    description: ["A good prepared fried rice win the soul of the customer"],
    steps:[
      "Cook the Jollof Rice according to the package instructions.",
      "per boiled your rice for about 20mins and then sieve the water from it there after",
      "per boil the cow liver and dice it into desirable size, add little quantity of veg oil into your port and met it for 2mins",
      "Blend the pepper and tomato with blender with a little water ",
      "pour the blending pepper and tomato into the hot vegetable oil and mix it together and add seasoning and Curry & Time to it with a little water",
      "allow it to boil for 4mins and then add back your per boil rice into it and cover it for another 15mins",
      "wash your carrot and green beans and dice them into very desirable size",
      "Add everything and stir it together for 2min for all the igredient to mix properly.",
      "then your food is ready to serve",
    ],
  },
  {
    id: "05",
    name: "Shawarma",
    image: require("../../assets/images/Shawarma.jpeg"),
    rating: "4.2",
    ingredients: ["Millet flour", "Vegetable Oil", "Salt and Seasoning", "Slice Onion", "Crumble Pepper", "Chicken Meat", "Bama cream" ],
    time: "15 mins",
    difficulty: "Fair",
    calories: "125 cal",
    color: "#48d612",
    description: ["A good prepared fried rice win the soul of the customer"],
    steps:[
      "Bake your Shawarma according to the package instructions.",
      "per boiled your rice for about 20mins and then sieve the water from it there after",
      "per boil the cow liver and dice it into desirable size, add little quantity of veg oil into your port and met it for 2mins",
      "Blend the green pepper with blender with a little water ",
      "pour the blending green pepper into the hot vegetable oil with your cow lever and mix it together and add seasoning to it with a little water",
      "allow it to boil for 4mins and then add back your per boil rice into it and cover it for another 15mins",
      "wash your carrot and green beans and dice them into very desirable size",
      "rinse your piece beans and open your can corn add everything and stir it together for 2min for all the igredient to mix properly.",
      "then your food is ready to serve",
    ],
  },
  {
    id: "06",
    name: "Piza",
    image: require("../../assets/images/piza.jpeg"),
    rating: "4.2",
    ingredients: ["Cereal flour", "Vegetable Oil", "Salt and Seasoning", "Slice Onion", "Crumble Pepper", "Egg" ],
    time: "10 mins",
    difficulty: "Fair",
    calories: "180 cal",
    color: "#d2b48c",
    description: ["A good prepared fried rice win the soul of the customer"],
    steps:[
      "Cook the Fried Rice according to the package instructions.",
      "per boiled your rice for about 20mins and then sieve the water from it there after",
      "per boil the cow liver and dice it into desirable size, add little quantity of veg oil into your port and met it for 2mins",
      "Blend the green pepper with blender with a little water ",
      "pour the blending green pepper into the hot vegetable oil with your cow lever and mix it together and add seasoning to it with a little water",
      "allow it to boil for 4mins and then add back your per boil rice into it and cover it for another 15mins",
      "wash your carrot and green beans and dice them into very desirable size",
      "rinse your piece beans and open your can corn add everything and stir it together for 2min for all the igredient to mix properly.",
      "then your food is ready to serve",
    ],
  },
  {
    id: "07",
    name: "Meat Pie",
    image: require("../../assets/images/meatpie.jpeg"),
    rating: "4.2",
    ingredients: ["Cereal flour", "Vegetable Oil", "Salt and Seasoning", "Slice Onion", "Crumble Pepper", "Dice Carots" ],
    time: "5 mins",
    difficulty: "Fair",
    calories: "105 cal",
    color: "#008080",
    description: ["A good prepared fried rice win the soul of the customer"],
    steps:[
      "Cook the Fried Rice according to the package instructions.",
      "per boiled your rice for about 20mins and then sieve the water from it there after",
      "per boil the cow liver and dice it into desirable size, add little quantity of veg oil into your port and met it for 2mins",
      "Blend the green pepper with blender with a little water ",
      "pour the blending green pepper into the hot vegetable oil with your cow lever and mix it together and add seasoning to it with a little water",
      "allow it to boil for 4mins and then add back your per boil rice into it and cover it for another 15mins",
      "wash your carrot and green beans and dice them into very desirable size",
      "rinse your piece beans and open your can corn add everything and stir it together for 2min for all the igredient to mix properly.",
      "then your food is ready to serve",
    ],
  },
  {
    id: "08",
    name: "Soucage Roll",
    image: require("../../assets/images/Soucage.jpeg"),
    rating: "4.2",
    ingredients: ["Cereal flour", "Vegetable Oil", "Salt and Seasoning", "Slice Onion", "Crumble Pepper", "Beef" ],
    time: "9 mins",
    difficulty: "Fair",
    calories: "250 cal",
    color: "#d8bfd8",
    description: ["A good prepared fried rice win the soul of the customer"],
    steps:[
      "Cook the Fried Rice according to the package instructions.",
      "per boiled your rice for about 20mins and then sieve the water from it there after",
      "per boil the cow liver and dice it into desirable size, add little quantity of veg oil into your port and met it for 2mins",
      "Blend the green pepper with blender with a little water ",
      "pour the blending green pepper into the hot vegetable oil with your cow lever and mix it together and add seasoning to it with a little water",
      "allow it to boil for 4mins and then add back your per boil rice into it and cover it for another 15mins",
      "wash your carrot and green beans and dice them into very desirable size",
      "rinse your piece beans and open your can corn add everything and stir it together for 2min for all the igredient to mix properly.",
      "then your food is ready to serve",
    ],
  },
  {
    id: "09",
    name: "Pounded Yam and Vegetable Soup",
    image: require("../../assets/images/PoundedYam.jpeg"),
    rating: "3.2",
    ingredients: ["Yam", "Palm Oil", "Salt and Seasoning", "Slice Onion", "Pepper", "Assorted meat" ],
    time: "48 mins",
    difficulty: "Fair",
    calories: "150 cal",
    color: "#ee82ee",
    description: ["A good prepared fried rice win the soul of the customer"],
    steps:[
      "Cook the Fried Rice according to the package instructions.",
      "per boiled your rice for about 20mins and then sieve the water from it there after",
      "per boil the cow liver and dice it into desirable size, add little quantity of veg oil into your port and met it for 2mins",
      "Blend the green pepper with blender with a little water ",
      "pour the blending green pepper into the hot vegetable oil with your cow lever and mix it together and add seasoning to it with a little water",
      "allow it to boil for 4mins and then add back your per boil rice into it and cover it for another 15mins",
      "wash your carrot and green beans and dice them into very desirable size",
      "rinse your piece beans and open your can corn add everything and stir it together for 2min for all the igredient to mix properly.",
      "then your food is ready to serve",
    ],
  },
];
